spring:
   data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.uri: mongodb://localhost/proxy-twitter
      mongo.repositories.enabled: true
      
      
twitter:
  username: emjwjOzNJM1VUZBE33pE6FCCJ
  password: DOZH47EQbfIIs0nnrErrwuvh06315XFRMPo37izCoPnzo5wnsI
  statusUrl: https://api.twitter.com/1.1/statuses/show.json?id=
  userUrl: https://api.twitter.com/1.1/users/show.json?screen_name=